defaults: &defaults
  :log_level: warn
  :mongo:
    :database: monk_mapper
    :host: localhost

:development:
  <<: *defaults
  :log_level: debug

:test:
  <<: *defaults

:production:
  <<: *defaults
